// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxA3j81_tNEDP10-vtyWOawHvEAvQMzVI',
    appId: '1:739777988856:web:576e9a22631374e9e0d30d',
    messagingSenderId: '739777988856',
    projectId: 'chattappproject-4407e',
    authDomain: 'chattappproject-4407e.firebaseapp.com',
    storageBucket: 'chattappproject-4407e.appspot.com',
    measurementId: 'G-KNYG2BQ4MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxsZn--J3gWsZz71ziFZa6c9XuL4hf2zE',
    appId: '1:739777988856:android:fbc1c57241a74e3de0d30d',
    messagingSenderId: '739777988856',
    projectId: 'chattappproject-4407e',
    storageBucket: 'chattappproject-4407e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8EWl-29TBwqFa4u675FMHfYU1N-DQ9Qo',
    appId: '1:739777988856:ios:b6d34661e662820ce0d30d',
    messagingSenderId: '739777988856',
    projectId: 'chattappproject-4407e',
    storageBucket: 'chattappproject-4407e.appspot.com',
    iosBundleId: 'com.example.chatappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8EWl-29TBwqFa4u675FMHfYU1N-DQ9Qo',
    appId: '1:739777988856:ios:f9e1b7e4316cdb24e0d30d',
    messagingSenderId: '739777988856',
    projectId: 'chattappproject-4407e',
    storageBucket: 'chattappproject-4407e.appspot.com',
    iosBundleId: 'com.example.chatappFlutter.RunnerTests',
  );
}
